version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - suever
  assignees:
  - suever
  ignore:
  - dependency-name: pydocstyle
    versions:
    - ">= 4.0.0.a"
    - "< 4.0.1"
  - dependency-name: python-engineio
    versions:
    - "> 3.8.2"
    - "< 3.8.3"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
