[tool.mypy]
python_version = "3.10"

strict_optional = true
show_error_codes = true
show_column_numbers = true
warn_no_return = true

warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
implicit_reexport = false
strict_equality = true
warn_unused_ignores = false

files = [
    "matl_online",
    "tests",
]

plugins = [
    "numpy.typing.mypy_plugin",
    "pydantic.mypy",
]

[tool.isort]
profile = "black"

[tool.black]
target-version = ["py37", "py38", "py39"]
extend-exclude = "(migrations)"
