version: 2
workflows:
  version: 2
  integration-tests:
    jobs:
      - integration-tests
  build:
    jobs:
      - docker
  test:
    jobs:
      - test-3.7
      - test-3.8
      - test-3.9
jobs:
  integration-tests:
    machine: 
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Run Integreation Tests
          command: docker-compose --profile testing run tests
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Octave
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq octave liboctave-dev libmpfr-dev
      - run:
          name: Install Yarn and Node
          command: |
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update -qq
            sudo apt-get install -qq yarn
      - run:
          name: Install Node dependencies
          command: |
            yarn install --frozen-lockfile
      - run:
          name: Install Python Dependencies
          command: |
            sudo pip install --upgrade pip setuptools wheel coveralls
            sudo pip install --only-binary=numpy,scipy -r requirements/dev.txt
      - run:
          name: Run tests
          command: |
            export PATH="$(yarn bin):$PATH"
            MATL_ONLINE_ENV=test python manage.py test
      - run:
          name: Run Linting
          command: |
            python manage.py lint
      - run:
          name: Report Coverage
          command: |
            coveralls
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster
  test-3.9:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster
