apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: matl-online
  labels:
    app: matl-online
spec:
  selector:
    matchLabels:
      app: matl-online
  template:
    metadata:
      name: web
      namespace: matl-online
      labels:
        app: matl-online
    spec:
      containers:
        - name: web
          image: "suever/matl-online:{{ .Values.CommitHash }}"
          command:
            - gunicorn
            - --worker-class=eventlet
            - --bind=0.0.0.0:5000
            # Flask-SocketIO requires only a single worker since eventlet does not
            # have sticky sessions
            - --workers=1
            - --threads=16
            - wsgi:app
          ports:
            - containerPort: 5000
          env:
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URI
                  name: secrets
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: secrets
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: secrets
            - name: EVENTLET_NO_GREENDNS
              value: "yes"
            - name: SOCKETIO_MESSAGE_QUEUE
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: secrets
            - name: MATL_ONLINE_ENV
              value: prod
          securityContext:
            runAsNonRoot: true
            runAsUser: 8877
          readinessProbe:
            tcpSocket:
              port: 5000
          livenessProbe:
            tcpSocket:
              port: 5000
