name: Python package

on: [push]

jobs:
  build:

    runs-on: debian-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Octave
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq octave liboctave-dev libmpfr-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel coveralls
        pip install --only-binary=numpy,scipy -r requirements/dev.txt
    - name: Lint with flake8
      run: |
        python manage.py lint
    - name: Test with pytest
      run: |
        py.test tests -v --cov=matl_online
