apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-restart
  namespace: matl-online
spec:
  concurrencyPolicy: Forbid
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: worker-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - '-n'
                - 'matl-online'
                - 'deployment/worker'
